### ISSUE TITLE
Method not working, got 10days

### ISSUE THREAD

**Issue by badr2004** [Eilte/Fiddler-Everywhere-Crack#1]
everything went well, till I executed the script, and got this:

+ $Acl.SetAccessRule($Ar)
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

[*] Fiddler Everywhere updater directory set-acl rules to all authenticated users 000!

I'm using Windows11

**Comment by Eilte** [comment]
Please check out the latest version, which works with the latest Fiddler Everywhere. Before that, you need to completely uninstall the old version.

**Comment by badr2004** [comment]
"Expiring on Dec 31, 2098"
It's working now, thank you
