### ISSUE TITLE
Disable auto update ?

### ISSUE THREAD

**Issue by asmirbe** [Eilte/Fiddler-Everywhere-Crack#2]
Is there any way to disable the auto update after opening fiddler ?
ty

**Comment by Eilte** [comment]
Please check the latest release notes

**Comment by blksmr** [comment]
perfect ty
is there any way to share the sources code of the binary ?
Cuz it's a bit sus

**Comment by Eilte** [comment]
> perfect ty is there any way to share the sources code of the binary ? Cuz it's a bit sus

The patch for 5.17+ is not made by me, it comes from https://www.52pojie.cn/thread-1948949-1-1.html, the original author did not make the source code public
